trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:

- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ocp-mgmt'
    cmd: 'oc new-project $(NMD-NAMESPACE)'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ocp-mgmt'
    cmd: 'oc new-app --name webapp-from-pipeline https://github.com/nmdkmd/web-app.git -n $(NMD-NAMESPACE)'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ocp-mgmt'
    cmd: 'oc expose svc webapp-from-pipeline --hostname webapp-from-pipeline.apps.mgmt.kmdstratus.com --name wfp'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      ROUTE=$(oc get route wfp -o jsonpath='{.spec.host}{"\n"}')
      echo "Webapp URL: http://$ROUTE"