# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ocp-mgmt'
    cmd: 'oc new-project $(NMD-NAMESPACE)'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ocp-mgmt'
    cmd: 'oc new-app --name webapp-from-pipeline https://github.com/nmdkmd/web-app.git -n $(NMD-NAMESPACE)'
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ocp-mgmt'
    cmd: 'oc expose svc webapp-from-pipeline --hostname webapp-from-pipeline.apps.mgmt.kmdstratus.com --name wfp'
- task: oc-cmd@4
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ocp-mgmt'
    inlineScript: |
     #!/bin/bash
     ROUTE: $(oc get route wfp -o jsonpath='{.spec.host}{"\n"}')
     echo "Webapp URL: http://$ROUTE"